### ISSUE TITLE
how can i choose "scan per file track gain" instead of "scan as single album"?

### ISSUE THREAD

**Issue by vibrasphere111** [Soukyuu/ddb_misc_replaygain_scan#10]
How can i do that?
Or is there no such choice at all? Please let me know!
Anyway, i appreciate ur work a lot!
hoping for ur answer!
matt

**Comment by Soukyuu** [comment]
Umm... To answer your question, you can't. This was only a basic implementation and I'm not maintaining it anymore.

The functionality was merged and improved upon in deadbeef itself, you shouldn't use this standalone version anymore.
