### ISSUE TITLE
Makefile patch

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [Soukyuu/ddb_misc_replaygain_scan#2]
These changes are required to build the plugin on the build service (deadbeef-plugin-builder):

https://raw.githubusercontent.com/Alexey-Yakovenko/deadbeef-plugin-builder/master/plugins/ddb_misc_replaygain_scan/build.patch

(the original patch didn't quite support cross-compilation, and wasn't linking to correct libraries)

**Comment by Soukyuu** [comment]
Sorry for the late reaction, was kind of busy.
