### ISSUE TITLE
Inclusion of the plugin in deadbeef player

### ISSUE THREAD

**Issue by Oleksiy-Yakovenko** [Soukyuu/ddb_misc_replaygain_scan#7]
Hi

_This is not a bug or a feature request, just information_

I started integrating the replaygain scanner into the main deadbeef player tree.

I merged the sources, with some modifications (so basically it's a fork).

It’s up to you whether you want to continue working on the plugin as a sepatate project, or submitting pull requests to deadbeef.

These are the changes that I made:
- rename to rg_scanner.so/.dylib
- change all mentions of “Replay Gain” to “ReplayGain” — that’s a more correct term
- change the APIs to be more backwards-compatibility-proof in the future, and easier to use in general
- use the new logging API (that makes the plugin only compatible with trunk, but that’s fine because meanwhile people may use your original plugin)
- use the new feature called “DDB_DECODER_HINT_RAW_SIGNAL”, which makes it possible to  calculate the correct peaks for MP3s, and prevent clipping
- fixed the buffer size calculation when decoding the streams
- avoid converting buffers when the format is already float32
- changed the way copyright information is written, to be more in line with other plugins
- fixed formatting to be more like what’s commonly used in deadbeef sources
- I could not figure out why you had to pass pretty much all input arguments as pointers, but I converted them to non-pointers

The GTK UI for the rg_scanner would not compile yet, and there’s no linux Makefile.am, or configure.ac support for it — I’m working on mac most of the time. But will fix all of it on linux eventually.

I will be adding Cocoa UI soon.

The plugin id is still “rgscanner”, but the name has been changed to “ReplayGain Scanner”.
Most likely I’ll have to change the id, to avoid potential conflicts with the original plugin.

This will ship as part of deadbeef 0.8.

Hope I covered everything. Please let me know if there’s anything I should know.

You can find it here: https://github.com/Alexey-Yakovenko/deadbeef/tree/master/plugins/rg_scanner

**Comment by Soukyuu** [comment]
I don't really have time to work on the plugin at the moment, and it has all the functionality I usually use, anyway. Should I start working on it again, I will most likely just submit patches to the deadbeef repo.

As for the pointers, I just like to have my data at one place and just pass the pointers to it, instead of copying everything.

**Comment by Oleksiy-Yakovenko** [comment]
When you're passing pointers to int32 variables -- the pointers are bigger, than the data they're pointing to. Furthermore, if the data is combined in a structure, only one pointer needs to be passed. So it's a win-win. Anyway, not gonna argue about this. I'm almost finished with the plugin upstream, so if you're interested - have a look at the new API.
